### ISSUE TITLE
honeycomb renders on square lattice, staples join in wrong helical phase (I think)

### ISSUE THREAD

**Issue by JonathanBath** [bhogberg/caDNAno2Blender#1]
This is a really useful tool, thankyou!

I have a couple of issues (using blender 2.91.2):

1. I think that staples connect in the wrong helical phase in the spaghetti view

2. Honeycomb lattice structures are rendered on a square lattice

**Comment by bhogberg** [comment]
Hm. For 2. Did you change from 'Square' to 'Honeycomb' in the dropdown menu?

For 1. if you didn't select the right lattice in the Lattice dropdown, the DNA rotations will be wrong. 

Note that for square lattice, staple connections will look worse the further away from 'base 0' you get. In this lattice, the helical twist of DNA doesn't perfectly match the turn number. Honeycomb uses 10.5 bases per turn, which is rather close to the natural twist of DNA. Square lattice uses, 10.666 or three full turns between crossovers. To visualize SQ structures faithfully, they should be twisted around the helical direction. This is a bit of a programming that I didn't do yet... A simple solution that I should add maybe is a user input box for the DNA helical twist.

**Comment by JonathanBath** [comment]
I think I've failed to install the module properly - I don't see any dropdown menu. I'll try again!

**Comment by bhogberg** [comment]
I added some comments on installation (from what I remember) in the README.

**Comment by JonathanBath** [comment]
I see the dropdown menu now! All works fine - the only problem was that I didn't know my way around blender
